server:
  port: 8090

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: bank-a
  cloud:
    consul:
      host: consul.yxcg.cc
      port: 8500
      discovery:
        serviceName: bank-a #注册到consul的服务名称

  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.101:3306/bank-a?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: Root!!123456